image: atlassian/default-image:2

clone: 
  depth: 1

pipelines:
  default:
    - step:
        script:
          - curl 'https://jenkins.flowingcode.com/git/notifyCommit?url='$BITBUCKET_GIT_SSH_ORIGIN
